const localizationString = {
  translation: {
    Calendar: {
      fromText: 'From:',
      toText: 'To:',
      selectStartDate: 'Select start date',
      selectEndDate: 'Select end date',
      todayText: 'Today',
      tomorrowText: 'Tomorrow',
      last7DaysText: 'Last 7 days',
      thisMonthText: 'This month',
      thisYearText: 'This year',
      last24Hours: 'Last 24 hours',
      yesterday: 'Yesterday',
      thisWeek: 'This week',
    },
    BottomNavigation: {
      favorites: 'Favorites',
      explore: 'Explore',
      more: 'More',
    },
    PrimaryHeader: {
      searchPlaceholderText: 'Search for articles',
    },
    IntroduceScreen: {
      signInText: 'Sign In',
      continueAsGuestText: 'Continue as guest',
    },
    ExploreScreen: {
      titleText: 'Your favorite publications',
      showMoreText: 'Show all',
      realtimeFeedText: 'Realtime feed',
      showMoreRealtimeFeedText: 'Read more',
      realtimeFeedItem: {
        wordsText: 'words',
      },
      latestPressReleaseTitleText: 'Latest newsletters',
      showMoreTextLatestPressRelease: 'Read more',
      latestPressReleaseItem: {
        recurringText: 'RECURRING',
      },
      belgaNow: 'Belga Now',
      belgaNowSubTitle: 'All of Belga’s updates, fresh of the wire',
      belgaNowSearchPlaceHolder: 'Search for Belga now',
      liveTitle: 'LIVE',
      allItems: 'All items',
      topic: 'Topic',
      languages: 'Languages',
      contentTypes: 'Content types',
      newsLettersSearchPlaceHolder: 'Search for newsletters',
      newsLetter: 'Newsletters',
      newsLettersDetailSearchPlaceHolder: 'Search in this newsletter',
      last30Days: 'Last 30 days',
      search: 'Search',
      last24Hours: 'Last 24 hours',
      savedSearch: 'SAVED SEARCHES',
      previousSearch: 'PREVIOUS SEARCHES',
    },
    NewspaperScreen: {
      pageText: 'Page',
      sidebar: {
        articlesPageText: 'ARTICLES PAGE',
      },
    },
    NewspaperDetailScreen: {
      sentimentText: 'SENTIMENT',
      mediaValueText: 'MEDIA VALUE',
      audienceReachText: 'AUDIENCE REACH',
      positioningText: 'POSITIONING',
      pageText: 'Page',
      wordsText: 'words',
      noticedIssueText: 'Noticed an issue with this article? Let us know!',
      reportIssueText: 'Report issue',
    },
    FavoritesScreen: {
      yourFavoritesText: 'Your favorites',
      searchPlaceholderNewsletters: 'Search for newsletters',
      allText: 'All',
      itemSelectedText: 'articles selected',
      clearSelectionText: 'Clear selection',
    },
    MoreScreen: {
      MyProfile: {
        myProfileText: 'My profile',
        accountSettingText: 'Account settings',
        changePasswordText: 'Change Password',
        helpText: 'Help',
        logoutText: 'Logout',
        accountSettingTab: {
          generalText: 'General',
          descriptionText:
            'Here you can control your general settings throughout Belga.press.',
          generalSettingsText: 'General settings',
          paginationSettingsText: 'Pagination settings',
          languageSettingsText: 'Language settings',
        },
        downloadText: 'Downloads',
      },
    },
    ShareScreen: {
      shareThisArticle: 'Share this article',
      shareLink: 'SHARE LINK',
      shareOnX: 'Share on X',
      shareOnLinkedin: 'Share on LinkedIn',
      emailYourTeam: 'E-mail your team',
      search: 'Search...',
      noRecipientsSelected: 'No recipients selected',
      noRecipientsDescription:
        'Search for recipients to add them to your selection.',
      selected: 'selected',
      clearSelection: 'Clear selection',
      notes: 'NOTES',
      send: 'SEND',
    },
  },
};

export default localizationString;
