export enum PATH_SCREEN {
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  USER_INFO_SCREEN = 'USER_INFO_SCREEN',
  PASSWORD_SCREEN = 'PASSWORD_SCREEN',
  OTP_SCREEN = 'OTP_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',

  NEWSPAPER_DETAIL_SCREEN = 'NEWSPAPER_DETAIL_SCREEN',

  REPORT_ISSUE_SCREEN = 'REPORT_ISSUE_SCREEN',

  // Main
  MAIN = 'MAIN',

  INTRODUCE_SCREEN = 'INTRODUCE_SCREEN',

  FAVORITES_SCREEN = 'FAVORITES_SCREEN',

  EXPLORE_SCREEN = 'EXPLORE_SCREEN',

  MORE_SCREEN = 'MORE_SCREEN',

  NEWSPAPER_SCREEN = 'NEWSPAPER_SCREEN',
}
