export enum QUERY_KEY {
  FAVORITES = 'FAVORITES',
  NEWSPAPER_DETAIL = 'NEWSPAPER_DETAIL',
  TOPICS = 'TOPICS',
  BELGA_NEWS_OBJECT = 'BELGA_NEWS_OBJECT',
  BELGA = 'BELGA',
  REALTIME_FEED = 'REALTIME_FEED',
  NEWSLETTER = 'NEWSLETTER',
  CONTACT = 'CONTACT',
  SHARE = 'SHARE',
}
